// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_utnkvA3gLxUWhQty7HBcjqAxn3Dfzyw',
    appId: '1:321174921144:web:ac40fa155a9af86aaa794d',
    messagingSenderId: '321174921144',
    projectId: 'valux-afd00',
    authDomain: 'valux-afd00.firebaseapp.com',
    storageBucket: 'valux-afd00.appspot.com',
    measurementId: 'G-PFX44L5Z7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3MSvWkBenabONGn3xJiEsYJtL6PIY-uk',
    appId: '1:321174921144:android:829972274d211b44aa794d',
    messagingSenderId: '321174921144',
    projectId: 'valux-afd00',
    storageBucket: 'valux-afd00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqKu2-gJ4Dn39wg1M7X7zQJDLF2fUlFLk',
    appId: '1:321174921144:ios:2a73ab70ca7a792eaa794d',
    messagingSenderId: '321174921144',
    projectId: 'valux-afd00',
    storageBucket: 'valux-afd00.appspot.com',
    iosBundleId: 'com.example.valux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqKu2-gJ4Dn39wg1M7X7zQJDLF2fUlFLk',
    appId: '1:321174921144:ios:2a73ab70ca7a792eaa794d',
    messagingSenderId: '321174921144',
    projectId: 'valux-afd00',
    storageBucket: 'valux-afd00.appspot.com',
    iosBundleId: 'com.example.valux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_utnkvA3gLxUWhQty7HBcjqAxn3Dfzyw',
    appId: '1:321174921144:web:5c0c30f12b37e72daa794d',
    messagingSenderId: '321174921144',
    projectId: 'valux-afd00',
    authDomain: 'valux-afd00.firebaseapp.com',
    storageBucket: 'valux-afd00.appspot.com',
    measurementId: 'G-3LR62R28F6',
  );

}